## Этап 1. Исследование данных (EDA)

In [1]:
# Загрузка библиотеки
import pandas as pd
import warnings
import matplotlib as plt
warnings.filterwarnings('ignore')

In [2]:
# Загрузка датасета
df = pd.read_csv("real_estate_data.csv")

In [18]:
# Вывод первых строк датасета
df.head(5)

,id,type,sub_type,start_date,end_date,listing_type,tom,building_age,total_floor_count,floor_no,room_count,size,address,furnished,heating_type,price,price_currency
0,1,Konut,Rezidans,12/10/18,1/9/19,2,30,0,20 ve üzeri,2,2+1,90.0,İstanbul/Kartal/Kordonboyu,NaN,Fancoil,3500.0,TRY
1,2,Konut,Daire,2/13/19,NaN,1,14,0,20 ve üzeri,20 ve üzeri,1+0,43.0,İstanbul/Kartal/Kordonboyu,NaN,Fancoil,490000.0,TRY
2,3,Konut,Daire,10/9/18,11/8/18,1,30,0,1,Yüksek Giriş,2+1,NaN,Tekirdağ/Çorlu/Reşadiye,NaN,Fancoil,155000.0,TRY
3,4,Konut,Rezidans,9/10/18,10/10/18,1,30,3,20 ve üzeri,20 ve üzeri,6+1,450.0,İstanbul/Beşiktaş/Levent,NaN,Fancoil,32500000.0,TRY
4,5,Konut,Rezidans,12/10/18,1/9/19,1,30,0,20 ve üzeri,2,2+1,90.0,İstanbul/Kartal/Kordonboyu,NaN,Fancoil,1450000.0,TRY

In [4]:
# Вывод размерности датасета
df.shape

(403487, 17)

В датасете всего 403487 строк и 17 столбцов

In [5]:
# Вывод краткой информации
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403487 entries, 0 to 403486
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 403487 non-null  int64
 1   type               403487 non-null  object
 2   sub_type           403487 non-null  object
 3   start_date         403487 non-null  object
 4   end_date           266298 non-null  object
 5   listing_type       403487 non-null  int64
 6   tom                403487 non-null  int64
 7   building_age       376097 non-null  object
 8   total_floor_count  375466 non-null  object
 9   floor_no           368191 non-null  object
 10  room_count         403487 non-null  object
 11  size               257481 non-null  float64
 12  address            403487 non-null  object
 13  furnished          0 non-null       float64
 14  heating_type       375517 non-null  object
 15  price              402772 non-null  float64
 16  price_currency     402772 non-null  object
dtypes: float64(3), int64(3), object(11)
memory usage: 52.3+ MB

Выведена краткая информация по датасету. 
Использумые типы данных:
- float64 - size, furnished, price;
- int64 - id, listing_type, tom;
- object - type, sub_type, start_date, end_date, building_age, total_floor_count, floor_no, room_count, address, heating_type, price currency.
  
В полях end_date, building_age, total_floor_count, floor_no, size, furnished, heating_type есть пустые строки. В поле furnished все строки пустые.

In [6]:
# Вывод типов данных по столбцам
df.dtypes

id                     int64
type                  object
sub_type              object
start_date            object
end_date              object
listing_type           int64
tom                    int64
building_age          object
total_floor_count     object
floor_no              object
room_count            object
size                 float64
address               object
furnished            float64
heating_type          object
price                float64
price_currency        object
dtype: object

In [8]:
# Вывод первых 5 строк
df.head(5)

,id,type,sub_type,start_date,end_date,listing_type,tom,building_age,total_floor_count,floor_no,room_count,size,address,furnished,heating_type,price,price_currency
0,1,Konut,Rezidans,12/10/18,1/9/19,2,30,0,20 ve üzeri,2,2+1,90.0,İstanbul/Kartal/Kordonboyu,NaN,Fancoil,3500.0,TRY
1,2,Konut,Daire,2/13/19,NaN,1,14,0,20 ve üzeri,20 ve üzeri,1+0,43.0,İstanbul/Kartal/Kordonboyu,NaN,Fancoil,490000.0,TRY
2,3,Konut,Daire,10/9/18,11/8/18,1,30,0,1,Yüksek Giriş,2+1,NaN,Tekirdağ/Çorlu/Reşadiye,NaN,Fancoil,155000.0,TRY
3,4,Konut,Rezidans,9/10/18,10/10/18,1,30,3,20 ve üzeri,20 ve üzeri,6+1,450.0,İstanbul/Beşiktaş/Levent,NaN,Fancoil,32500000.0,TRY
4,5,Konut,Rezidans,12/10/18,1/9/19,1,30,0,20 ve üzeri,2,2+1,90.0,İstanbul/Kartal/Kordonboyu,NaN,Fancoil,1450000.0,TRY

In [9]:
# Вывод последних 5 строк
df.tail()

,id,type,sub_type,start_date,end_date,listing_type,tom,building_age,total_floor_count,floor_no,room_count,size,address,furnished,heating_type,price,price_currency
403482,403483,Konut,Daire,9/18/18,NaN,2,162,NaN,NaN,NaN,+,NaN,İstanbul/Sultanbeyli/Adil,NaN,NaN,1500.0,TRY
403483,403484,Konut,Daire,10/11/18,NaN,1,139,NaN,NaN,NaN,2+1,NaN,Sakarya/Adapazarı/Cumhuriyet,NaN,NaN,120000.0,TRY
403484,403485,Konut,Daire,11/22/18,NaN,1,97,NaN,NaN,NaN,1+1,NaN,Antalya/Alanya/Saray,NaN,NaN,48000.0,EUR
403485,403486,Konut,Daire,2/21/19,NaN,2,6,NaN,NaN,NaN,2+1,2.0,Aydın/Kuşadası/Türkmen,NaN,NaN,900.0,TRY
403486,403487,Konut,Daire,1/15/19,1/18/19,1,3,NaN,NaN,NaN,3+1,140.0,Kayseri/Melikgazi/Alpaslan,NaN,NaN,210000.0,TRY

In [10]:
# Вывод случайных 5 строк
df.sample(5)

,id,type,sub_type,start_date,end_date,listing_type,tom,building_age,total_floor_count,floor_no,room_count,size,address,furnished,heating_type,price,price_currency
226584,226585,Konut,Daire,9/21/18,11/20/18,1,60,6-10 arası,5,4,2+1,NaN,Tekirdağ/Çorlu/Muhittin,NaN,Kombi (Doğalgaz),215000.0,TRY
252911,252912,Konut,Daire,2/12/19,NaN,1,15,16-20 arası,8,6,2+1,120.0,Samsun/İlkadım/Ulugazi,NaN,Kombi (Doğalgaz),160000.0,TRY
348333,348334,Konut,Daire,1/18/19,2/11/19,1,24,16-20 arası,4,3,3+1,120.0,İzmir/Seferihisar/Camikebir,NaN,Soba (Kömür),230000.0,TRY
379623,379624,Konut,Daire,11/13/18,1/14/19,1,62,NaN,NaN,NaN,2+1,80.0,İstanbul/Tuzla/Postane,NaN,NaN,580000.0,TRY
68699,68700,Konut,Daire,10/8/18,11/29/18,1,52,4,5,5,3+1,190.0,Mersin/Mezitli/Yeni,NaN,Klima,330000.0,TRY

Описать источник данных, получить критерии измерения, определить целевую
переменную (цену).

In [7]:
df.describe()

,id,listing_type,tom,size,furnished,price
count,403487.00000,403487.000000,403487.000000,257481.000000,0.0,4.027720e+05
mean,201744.00000,1.294235,57.022739,279.349094,NaN,3.546417e+05
std,116476.80837,0.467733,44.358933,9429.195331,NaN,4.809503e+06
min,1.00000,1.000000,0.000000,1.000000,NaN,-2.500000e+02
25%,100872.50000,1.000000,29.000000,85.000000,NaN,2.500000e+03
50%,201744.00000,1.000000,40.000000,110.000000,NaN,1.990000e+05
75%,302615.50000,2.000000,90.000000,140.000000,NaN,3.420000e+05
max,403487.00000,3.000000,180.000000,948235.000000,NaN,2.000000e+09